POST http://localhost:8080/api/v1/auth/signup
Content-Type: application/json

{
  "loginId": "migujeong2",
  "password": "여덟글자넘어야됨1",
  "email": "abc2@abc.com",
  "nickname": "미구2",
  "birthDate": "2022-01-18T18:25:40",
  "phone": "01012345670",
  "role": "USER"
}


### read user
GET http://localhost:8080/api/v1/users/migujeong2


### 성공 200
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "loginId": "migujeong2",
  "password": "여덟글자넘어야됨1"
}

### 로그인 실패 401
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "loginId": "notchanmi",
  "password": "1234"
}

### 로그인 실패 401

POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "loginId": "migujeong2",
  "password": "1234"
}


### 로그인 정보 확인
GET http://localhost:8080/api/v1/users/me

### 로그아웃
POST http://localhost:8080/api/v1/users/auth/logout
